name: Build CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          echo ${{ secrets.SIGN_KEY }} | base64 -d > key.jks
          git submodule update --init --recursive
          ./gradlew :app:assembleRelease
        env:
          KEYSTORE_PATH: "../key.jks"
          KEYSTORE_PASSWORD: ${{ secrets.SIGN_PASS }}
          KEY_ALIAS: ${{ secrets.SIGN_ALIAS }}
          KEY_PASSWORD: ${{ secrets.ALIA_PASS }}
          CommitNumber: ${{ github.run_number }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: ${{ !github.event.pull_request }}
        with:
          path: 'app/build/outputs/apk/release/app-release.apk'
          name: ChatWithMe-v${{ github.run_number }}
      - name: mkd
        uses: fifsky/ssh-action@master
        with:
          command: |
            mkdir ${{ secrets.DEPLOY_DEST }}v${{ github.run_number }}/
          host: ${{ secrets.SERVER_IP }}
          user: ${{ secrets.SERVER_USERNAME }}
          port: 22
          pass: ${{ secrets.SERVER_PASSWORD }}
      - name: Remote SSH Pusblish
        uses: nerd4ever/ssh-action@master
        with:
          from: ./app/build/outputs/apk/release/*.*
          to:  ${{ secrets.DEPLOY_DEST }}v${{ github.run_number }}/
          sync: local
          host: ${{ secrets.SERVER_IP }}
          user: ${{ secrets.SERVER_USERNAME }}
          port: 22
          pass: ${{ secrets.SERVER_PASSWORD }}
